package com.example.stylemate

import android.content.Intent
import android.os.Bundle
import android.view.View
import android.widget.ImageButton
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.google.android.material.button.MaterialButton
import com.google.android.material.floatingactionbutton.FloatingActionButton
import com.google.gson.Gson

class ResultActivity : AppCompatActivity() {

    // UI elements
    private lateinit var textGroomingTip: TextView
    private lateinit var textOutfitSuggestion: TextView
    private lateinit var textBeardTip: TextView
    private lateinit var textFragrance: TextView
    private lateinit var textQuote: TextView
    private lateinit var btnShare: MaterialButton
    private lateinit var btnBackToHome: MaterialButton
    private lateinit var btnBack: ImageButton
    private lateinit var fabInfo: FloatingActionButton

    // Current recommendation
    private var currentRecommendation: StyleRecommendation? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_result)

        // Initialize views
        initViews()

        // Get recommendation from intent
        getRecommendationFromIntent()

        // Set up listeners
        setUpListeners()
    }

    private fun initViews() {
        textGroomingTip = findViewById(R.id.text_grooming_tip)
        textOutfitSuggestion = findViewById(R.id.text_outfit_suggestion)
        textBeardTip = findViewById(R.id.text_beard_tip)
        textFragrance = findViewById(R.id.text_fragrance)
        textQuote = findViewById(R.id.text_quote)
        btnShare = findViewById(R.id.btn_share)
        btnBackToHome = findViewById(R.id.btn_back_to_home)
        btnBack = findViewById(R.id.btn_back)
        fabInfo = findViewById(R.id.fab_info)
    }

    private fun getRecommendationFromIntent() {
        val recommendationJson = intent.getStringExtra("recommendation")
        if (recommendationJson != null) {
            try {
                val gson = Gson()
                currentRecommendation = gson.fromJson(recommendationJson, StyleRecommendation::class.java)
                updateRecommendationsUI(currentRecommendation!!)
            } catch (e: Exception) {
                Toast.makeText(this, "Error loading recommendations", Toast.LENGTH_SHORT).show()
                finish()
            }
        } else {
            Toast.makeText(this, "No recommendations found", Toast.LENGTH_SHORT).show()
            finish()
        }
    }

    private fun updateRecommendationsUI(recommendation: StyleRecommendation) {
        textGroomingTip.text = recommendation.groomingTip
        textOutfitSuggestion.text = recommendation.outfitSuggestion
        textBeardTip.text = recommendation.beardTip
        textFragrance.text = recommendation.fragrance
        textQuote.text = recommendation.quote
    }

    private fun setUpListeners() {
        // Share button click listener
        btnShare.setOnClickListener {
            shareCurrentLook()
        }

        // Back to home button click listeners (two options)
        btnBackToHome.setOnClickListener {
            finish()
        }

        btnBack.setOnClickListener {
            finish()
        }

        // Info button click listener
        fabInfo.setOnClickListener {
            showInfoModal()
        }
    }

    private fun shareCurrentLook() {
        currentRecommendation?.let { recommendation ->
            val shareText = """
                StyleMate Recommendations:
                
                👔 Outfit: ${recommendation.outfitSuggestion}
                
                🧼 Grooming: ${recommendation.groomingTip}
                
                🧔 Beard Care: ${recommendation.beardTip}
                
                🧴 Fragrance: ${recommendation.fragrance}
                
                💬 Remember: ${recommendation.quote}
                
                - Generated by StyleMate App
            """.trimIndent()

            val shareIntent = Intent().apply {
                action = Intent.ACTION_SEND
                putExtra(Intent.EXTRA_TEXT, shareText)
                type = "text/plain"
            }

            startActivity(Intent.createChooser(shareIntent, "Share your style"))
            Toast.makeText(this, getString(R.string.notification_shared), Toast.LENGTH_SHORT).show()
        }
    }

    private fun showInfoModal() {
        val infoModalFragment = InfoModelFragment.newInstance()
        infoModalFragment.show(supportFragmentManager, InfoModelFragment.TAG)
    }
}